### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/zipkin-php#26]
- PHP related tags
- Tracer::setNoop

**Comment by adriancole** [comment]
By the way.. in brave we set Tracing.noop (not Tracer.noop) because there are other components available that might want to go noop available in Tracing. Also from a configuration pov everything is centralized in Tracing... dont want a user of Tracer feeling tempted to disable the tracing system by misunderstanding scope.

**Comment by jcchavezs** [comment]
Yeah, great feedback. This one was a mistake so I closed it because I had created this one: https://github.com/jcchavezs/zipkin-php/issues/28.
