### ISSUE TITLE
Remove ipv4 required parameter

### ISSUE THREAD

**Issue by beberlei** [jcchavezs/zipkin-php#5]
Is IPv4 a required parameter in zipkin? I don't have a valid one in my docker container according to `filter_var(FILTER_VALIDATE_IP)`, so everything fails, because the API requires it wheras ipv6 is optional.

The validation should be less strict and just take the parameters and pass them on.

**Comment by jcchavezs** [comment]
According to https://github.com/openzipkin/brave/blob/master/archive/brave-core/src/main/java/com/twitter/zipkin/gen/Endpoint.java#L21 ipv4 it is required however maybe the problem is the validation. I see two possibilities:

- Remove the required for the parameter
- Fix the validation

What do you think @beberlei? Any though on this @adriancole?

**Comment by adriancole** [comment]
in v2 format we make it explicit that no IP is required (neither ipv4 nor ipv6 as serviceName by itself is useful). In v1 format you can give a value of 0 for ipv4 if you don't know one. In any case you can eliminate if from json.

**Comment by jcchavezs** [comment]
:+1: i Will make it optional.
